# Generated by Django 4.0.4 on 2022-06-14 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_shippingaddress_name_shippingaddress_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductThumbnails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thumbnails', models.FileField(upload_to='images/')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
