# Generated by Django 4.0.4 on 2022-06-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_thumbnails_delete_productthumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnails',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
