# Generated by Django 4.0.4 on 2022-06-15 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='contactNumber',
            new_name='telephone',
        ),
        migrations.AlterField(
            model_name='product',
            name='saleNumber',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000000000000000000000000000000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
