export const products = [
  {
    _id: "1",
    name: "camera",
    image: "https://m.media-amazon.com/images/I/71rEGALiLfL._AC_SX679_.jpg",
    description: "good one",
    brand: "sonny",
    category: "cams",
    price: 269.99,
    stockCount: 20,
    rating: 5,
    reviewsCount: 50,
  },
  {
    _id: "2",
    name: "camera",
    image: "https://m.media-amazon.com/images/I/71rEGALiLfL._AC_SX679_.jpg",
    description: "good one",
    brand: "sonny",
    category: "cams",
    price: 269.99,
    stockCount: 20,
    rating: 5,
    reviewsCount: 50,
  },
  {
    _id: "3",
    name: "camera",
    image: "https://m.media-amazon.com/images/I/71rEGALiLfL._AC_SX679_.jpg",
    description: "good one",
    brand: "sonny",
    category: "cams",
    price: 269.99,
    stockCount: 20,
    rating: 5,
    reviewsCount: 50,
  },
  {
    _id: "4",
    name: "camera",
    image: "https://m.media-amazon.com/images/I/71rEGALiLfL._AC_SX679_.jpg",
    description: "good one",
    brand: "sonny",
    category: "cams",
    price: 269.99,
    stockCount: 20,
    rating: 5,
    reviewsCount: 50,
  },
  {
    _id: "5",
    name: "camera",
    image: "https://m.media-amazon.com/images/I/71rEGALiLfL._AC_SX679_.jpg",
    description: "good one",
    brand: "sonny",
    category: "cams",
    price: 269.99,
    stockCount: 20,
    rating: 5,
    reviewsCount: 50,
  },
  {
    _id: "6",
    name: "camera",
    image: "https://m.media-amazon.com/images/I/71rEGALiLfL._AC_SX679_.jpg",
    description: "good one",
    brand: "sonny",
    category: "cams",
    price: 269.99,
    stockCount: 20,
    rating: 5,
    reviewsCount: 50,
  },
];
